apiVersion: v1
kind: Service
metadata:
  labels:
    run: postgres
  name: postgres-service
spec:
  ports:
  - port: 5432
    nodePort: 32000
    targetPort: 5432
    protocol: TCP
  selector:
    app: postgres
  type: NodePort

  